In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd 
import gc
import os 
import tensorflow as tf

In [3]:
classwise_data = pd.read_csv(r'../classwiseoutputinputv3.csv')

/home/nayan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
"""## Preparing train & val set"""
#print(classwise_data)
from sklearn.model_selection import train_test_split

(X_date_c)=classwise_data['X_date_c'].tolist()
(X_letters_c)=classwise_data['X_letters_c'] [:152795].tolist()
(X_cardinal_c)=classwise_data['X_cardinal_c'] [:133744].tolist()
(X_verbatim_c)= classwise_data['X_verbatim_c'][:78108].tolist()
(X_decimal_c)= classwise_data['X_decimal_c'][:9821].tolist()
(X_measure_c)=classwise_data['X_measure_c'][:14783].tolist()
(X_money_c)=classwise_data['X_money_c'][:6128].tolist()
(X_ordinal_c)=classwise_data['X_ordinal_c'] [:12703].tolist()
(X_time_c)=classwise_data['X_time_c'] [:1465].tolist()
(X_electronic_c)=classwise_data['X_electronic_c'] [:5162].tolist()
(X_digit_c)=classwise_data['X_digit_c'] [:5442].tolist()
(X_fraction_c)=classwise_data['X_fraction_c'] [:1196].tolist()
(X_telephone_c)=classwise_data['X_telephone_c'][:4024].tolist()
(X_address_c)=classwise_data['X_address_c'] [:522].tolist()


(X_date)=classwise_data['X_date'].tolist()
(X_letters)=classwise_data['X_letters'] [:152795].tolist()
(X_cardinal)=classwise_data['X_cardinal'] [:133744].tolist()
(X_verbatim)= classwise_data['X_verbatim'][:78108].tolist()
(X_decimal)= classwise_data['X_decimal'][:9821].tolist()
(X_measure)=classwise_data['X_measure'][:14783].tolist()
(X_money)=classwise_data['X_money'][:6128].tolist()
(X_ordinal)=classwise_data['X_ordinal'] [:12703].tolist()
(X_time)=classwise_data['X_time'] [:1465].tolist()
(X_electronic)=classwise_data['X_electronic'] [:5162].tolist()
(X_digit)=classwise_data['X_digit'] [:5442].tolist()
(X_fraction)=classwise_data['X_fraction'] [:1196].tolist()
(X_telephone)=classwise_data['X_telephone'][:4024].tolist()
(X_address)=classwise_data['X_address'] [:522].tolist()



(y_date)=classwise_data['y_date'].tolist() 
(y_letters)=classwise_data['y_letters'] [:152795].tolist()
(y_cardinal)=classwise_data['y_cardinal']  [:133744].tolist()
(y_verbatim)=classwise_data['y_verbatim'][:78108].tolist()
(y_decimal)=classwise_data['y_decimal'][:9821].tolist()
(y_measure)=classwise_data['y_measure'][:14783].tolist()
(y_money)=classwise_data['y_money'] [:6128].tolist()
(y_ordinal)=classwise_data['y_ordinal']  [:12703].tolist()
(y_time)=classwise_data['y_time'] [:1465].tolist()
(y_electronic)=classwise_data['y_electronic']  [:5162].tolist()
(y_digit)=classwise_data['y_digit']  [:5442].tolist()
(y_fraction)=classwise_data['y_fraction'][:1196].tolist()
(y_telephone)=classwise_data['y_telephone'] [:4024].tolist()
(y_address)=classwise_data['y_address'] [:522].tolist()



In [5]:


X_train_date_c, X_val_date_c, X_train_date, X_val_date, y_train_date, y_val_date = train_test_split(X_date_c,X_date, y_date, test_size=0.015, random_state=42)
X_train_letters_c, X_val_letters_c, X_train_letters, X_val_letters, y_train_letters, y_val_letters = train_test_split(X_letters_c,X_letters, y_letters, test_size=0.015, random_state=42)
X_train_cardinal_c, X_val_cardinal_c,X_train_cardinal, X_val_cardinal, y_train_cardinal, y_val_cardinal = train_test_split(X_cardinal_c,X_cardinal, y_cardinal, test_size=0.015, random_state=42)
X_train_verbatim_c, X_val_verbatim_c,X_train_verbatim, X_val_verbatim, y_train_verbatim, y_val_verbatim = train_test_split(X_verbatim_c,X_verbatim, y_verbatim, test_size=0.015, random_state=42)
X_train_decimal_c, X_val_decimal_c,X_train_decimal, X_val_decimal, y_train_decimal, y_val_decimal = train_test_split(X_decimal_c,X_decimal, y_decimal, test_size=0.015, random_state=42)
X_train_measure_c, X_val_measure_c,X_train_measure, X_val_measure, y_train_measure, y_val_measure = train_test_split(X_measure_c,X_measure, y_measure, test_size=0.015, random_state=42)
X_train_money_c, X_val_money_c,X_train_money, X_val_money, y_train_money, y_val_money = train_test_split(X_money_c,X_money, y_money, test_size=0.015, random_state=42)
X_train_ordinal_c, X_val_ordinal_c,X_train_ordinal, X_val_ordinal, y_train_ordinal, y_val_ordinal = train_test_split(X_ordinal_c, X_ordinal, y_ordinal, test_size=0.015, random_state=42)
X_train_time_c, X_val_time_c,X_train_time, X_val_time, y_train_time, y_val_time = train_test_split(X_time_c, X_time, y_time, test_size=0.015, random_state=42)
X_train_electronic_c, X_val_electronic_c,X_train_electronic, X_val_electronic, y_train_electronic, y_val_electronic = train_test_split(X_electronic_c, X_electronic, y_electronic, test_size=0.015, random_state=42)
X_train_digit_c, X_val_digit_c,X_train_digit, X_val_digit, y_train_digit, y_val_digit = train_test_split(X_digit_c,X_digit, y_digit, test_size=0.015, random_state=42)
X_train_fraction_c, X_val_fraction_c, X_train_fraction, X_val_fraction, y_train_fraction, y_val_fraction = train_test_split(X_fraction_c, X_fraction, y_fraction, test_size=0.015, random_state=42)
X_train_telephone_c, X_val_telephone_c,X_train_telephone, X_val_telephone, y_train_telephone, y_val_telephone = train_test_split(X_telephone_c,X_telephone, y_telephone, test_size=0.015, random_state=42)
X_train_address_c, X_val_address_c,X_train_address, X_val_address, y_train_address, y_val_address = train_test_split(X_address_c, X_address, y_address, test_size=0.015, random_state=42)


X_train_c =X_train_date_c+X_train_letters_c+X_train_cardinal_c+X_train_verbatim_c+X_train_decimal_c+X_train_measure_c+X_train_money_c+X_train_ordinal_c+X_train_time_c+X_train_electronic_c+X_train_digit_c+ X_train_fraction_c+X_train_telephone_c+X_train_address_c
X_train =X_train_date+X_train_letters+X_train_cardinal+X_train_verbatim+X_train_decimal+X_train_measure+X_train_money+X_train_ordinal+X_train_time+X_train_electronic+X_train_digit+ X_train_fraction+X_train_telephone+X_train_address
y_train= y_train_date+y_train_letters+y_train_cardinal+y_train_verbatim+y_train_decimal+y_train_measure+y_train_money+y_train_ordinal+y_train_time+y_train_electronic+y_train_digit+y_train_fraction+y_train_telephone+y_train_address


X_val_c =X_val_date_c+X_val_letters_c+X_val_cardinal_c+X_val_verbatim_c+X_val_decimal_c+X_val_measure_c+X_val_money_c+X_val_ordinal_c+X_val_time_c+X_val_electronic_c+X_val_digit_c+ X_val_fraction_c+X_val_telephone_c+X_val_address_c
X_val =X_val_date+X_val_letters+X_val_cardinal+X_val_verbatim+X_val_decimal+X_val_measure+X_val_money+X_val_ordinal+X_val_time+X_val_electronic+X_val_digit+ X_val_fraction+X_val_telephone+X_val_address
y_val= y_val_date+y_val_letters+y_val_cardinal+y_val_verbatim+y_val_decimal+y_val_measure+y_val_money+y_val_ordinal+y_val_time+y_val_electronic+y_val_digit+y_val_fraction+y_val_telephone+y_val_address





In [6]:
print(X_val[:10])
for i in range(len(X_train)):
    X_train[i] = X_train[i].strip()
    y_train[i] = y_train[i].strip()
    X_train_c[i]= X_train_c[i].strip()



for i in range(len(X_val)):
    X_val[i] = X_val[i].strip()
    y_val[i] = y_val[i].strip()
    X_val_c[i]= X_val_c[i].strip()
print(X_val[:10])

['362 ad  ', '2011 ', '2011 ', 'february 1  2007 ', '1910 ', '18 june 1946 ', '1400 ', '2009 ', '1997 ', '19 march 1875 ']
['362 ad', '2011', '2011', 'february 1  2007', '1910', '18 june 1946', '1400', '2009', '1997', '19 march 1875']


In [7]:
eval_data = [X_val_c, X_val,y_val]

In [8]:


X_train_c,X_test_c,X_train,X_test,y_train,y_test = train_test_split( X_train_c,X_train, y_train,test_size=0.0015)

print(len(X_test_c))
datasetLength = 10000 #max data size 673000

X_nnrmlzd_c= X_train_c[0:datasetLength]
X_nnrmlzd= X_train[0:datasetLength]
X_nrmlzd = y_train[0:datasetLength]



X_train_c,_,X_train,_,y_train, _ = train_test_split( X_nnrmlzd_c,X_nnrmlzd, X_nrmlzd,test_size=0.0000000001) #shuffles all data

X_nnrmlzd_c=X_train_c 
X_nnrmlzd =X_train
X_nrmlzd =y_train

print(X_nnrmlzd_c[1:4])
print(X_nnrmlzd[1:4])
print(X_nrmlzd[1:4])
print(len(X_nnrmlzd_c),len(X_nnrmlzd),len(X_nrmlzd))

pad_size=1
maxlen1 = 6
maxlen2 = 10  #10 represents number of word generated from one not normalized word


1011
['of 8 061', '1797', '2015 10 12']
['8 061', '1797', '2015 10 12']
['eight thousand sixty one', 'seventeen ninety seven', 'the twelfth of october twenty fifteen']
9999 9999 9999


### change after this for changing model, all before is to preparing and importing dataset

In [9]:

"""### Tokenize text and padding"""

from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from numpy import array
from numpy import argmax

tokenizer1 = Tokenizer(num_words=datasetLength )
tokenizer2 = Tokenizer(num_words=datasetLength )
tokenizer1.fit_on_texts(X_nnrmlzd_c)
tokenizer2.fit_on_texts(X_nrmlzd)


X_nnrmlzd = tokenizer1.texts_to_sequences(X_nnrmlzd_c)
X_nrmlzd =  tokenizer2.texts_to_sequences(X_nrmlzd)

vocab_size1 = len(tokenizer1.word_index) + 1  # Adding 1 because of reserved 0 index
vocab_size2 = len(tokenizer2.word_index) + 1


X_nnrmlzd = pad_sequences(X_nnrmlzd, padding='post', maxlen=maxlen1)
X_nrmlzd = pad_sequences(X_nrmlzd, padding='post', maxlen=maxlen2)

print(vocab_size1,vocab_size2)

print(X_nnrmlzd[:5])
print(X_nrmlzd[:5])

X_train=(X_nnrmlzd)
y_train=(X_nrmlzd)

5699 411
[[   3  257  716    0    0    0]
 [   6   42 1531    0    0    0]
 [1532    0    0    0    0    0]
 [  31   28   55    0    0    0]
 [  95    0    0    0    0    0]]
[[34 34 19  0  0  0  0  0  0  0]
 [13  4 37  5  0  0  0  0  0  0]
 [78 21 14  0  0  0  0  0  0  0]
 [ 6 88  7 53  2 47  0  0  0  0]
 [ 1  4  1  0  0  0  0  0  0  0]]


In [10]:
y = to_categorical(y_train, num_classes= vocab_size2)

### define model and train

In [11]:
# Check keras version
import tensorflow as tf
from tensorflow import keras
gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except:
        # Invalid device or cannot modify virtual devices once initialized.
        pass
from keras.layers import Bidirectional
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense,Lambda
from keras import backend as K
from keras.layers import Embedding
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from tensorflow.keras.optimizers import Adam
from numpy.random import shuffle

### Seq2seq model encoder-decoder based with bidirectional LSTM

In [12]:
'''
# define generator model
def define_generator(src_vocab, tar_vocab, src_timesteps, tar_timesteps, n_units):
	model = Sequential()
	model.add(Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True))
	model.add(Bidirectional(LSTM(n_units)))
	model.add(RepeatVector(tar_timesteps))
	model.add(Bidirectional(LSTM(n_units, return_sequences=True)))
	model.add(TimeDistributed(Dense(tar_vocab, activation='softmax')))
	# compile model
	model.compile(optimizer='adam', loss='categorical_crossentropy',metrics= ['accuracy'], run_eagerly=False)
	# summarize defined model

	return model

'''


"\n# define generator model\ndef define_generator(src_vocab, tar_vocab, src_timesteps, tar_timesteps, n_units):\n\tmodel = Sequential()\n\tmodel.add(Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True))\n\tmodel.add(Bidirectional(LSTM(n_units)))\n\tmodel.add(RepeatVector(tar_timesteps))\n\tmodel.add(Bidirectional(LSTM(n_units, return_sequences=True)))\n\tmodel.add(TimeDistributed(Dense(tar_vocab, activation='softmax')))\n\t# compile model\n\tmodel.compile(optimizer='adam', loss='categorical_crossentropy',metrics= ['accuracy'], run_eagerly=False)\n\t# summarize defined model\n\n\treturn model\n\n"

### Adding attention mechanism

In [13]:
 from keras.layers.recurrent import Recurrent, _time_distributed_dense

ImportError: cannot import name 'Recurrent'

In [ ]:
from attention_decoder import AttentionDecoder

In [ ]:
def define_generator(src_vocab, tar_vocab, src_timesteps, tar_timesteps, n_units):
    

    model = Sequential()
    model.add(LSTM(150, input_shape=(n_timesteps_in, n_features), return_sequences=True))
    model.add(AttentionDecoder(150, n_features))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    '''
    # define model
    model = Sequential()
    model.add(LSTM(150, input_shape=(n_timesteps_in, n_features)))
    model.add(RepeatVector(n_timesteps_in))
    model.add(LSTM(150, return_sequences=True))
    model.add(TimeDistributed(Dense(n_features, activation='softmax')))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])'''

    model = Sequential()
	model.add(Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True))
	model.add(Bidirectional(LSTM(n_units, return_sequences=True)))
    model.add(AttentionDecoder(n_units, tar_vocab))
    
    '''
    model.add(RepeatVector(tar_timesteps))
	model.add(Bidirectional(LSTM(n_units, return_sequences=True)))
	model.add(TimeDistributed(Dense(tar_vocab, activation='softmax')))
    '''
	
	# compile model
	model.compile(optimizer='adam', loss='categorical_crossentropy',metrics= ['accuracy'], run_eagerly=False)
	# summarize defined model

	
	return model

In [ ]:
#tf.compat.v1.disable_eager_execution()
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

In [ ]:
model = define_generator(vocab_size1,vocab_size2,maxlen1,maxlen2,256)


In [ ]:
model.summary()

In [ ]:
history = model.fit(X_train,y, batch_size = 128, epochs = 5, verbose = 2,validation_split= 0.0015,shuffle= True)

Inferencing and scoring

In [ ]:

from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction
from jiwer import wer 
from sklearn.metrics import accuracy_score

def average_bleu(refa, hypa):
    
  smoothie = SmoothingFunction().method2
  n= len(refa)
  net =0
  for i in range(n):
    
    a= sentence_bleu([refa[i]],hypa[i], smoothing_function=smoothie)
    net= net + a
  me = net/n
  return me

def acc_scorer(y_pred,y_true):
    a= 0
    for i in range(len(y_true)):
        a+= accuracy_score(y_true[i],y_pred[i])
    a= a/len(y_true)
    return a
def accuracy_printerXY(X,y_true,gen):
    inp= tokenizer1.texts_to_sequences(X)
    inp =pad_sequences(inp, padding='post', maxlen=maxlen1)
    out = gen.predict(inp)
    out = np.argmax(out,axis=-1)
    text_out= tokenizer2.sequences_to_texts(out)
    ground_truth =y_true

    ground_truth_seq = tokenizer2.texts_to_sequences(ground_truth)
    ground_truth_seq =pad_sequences(ground_truth_seq, padding='post', maxlen=maxlen2)
    text_out= np.asarray(text_out)
    ground_truth= ground_truth
    text_out= text_out.tolist()
    
    acc= acc_scorer(out,ground_truth_seq)

    print(text_out[:10])
    print('------------------------------')
    print(ground_truth[:10])
    w= wer(ground_truth,text_out)
    print('WER is:', w*100)

    print('Accuracy is:',acc)
    smoothie = SmoothingFunction().method4
    score = average_bleu(ground_truth,text_out)
    print('Average BLEU score is: ',score)
    print('\n')
    
    return w,acc,score

In [ ]:
edges = [3876 , 2292 , 2007 , 1172 , 148 , 222 , 92 , 191 , 22 , 78 , 82 , 18 , 61 , 8]
classes =['date','letters','cardinal','verbatim','decimal','measure','money','ordinal','time',
          'electronic','digit', 'fraction','telephone','address']

terminal=0
initial =0

wer_classwise = []
acc_classwise = []
bleu_classwise = []
for i in range(14):
    
    terminal= initial + edges[i]
    print('For class: ',classes[i])
    wr, acc, bleu = accuracy_printerXY(X_val_c[initial:terminal],y_val[initial:terminal],model)
    wer_classwise.append(wr)
    acc_classwise.append(acc)
    bleu_classwise.append(bleu)
    
    initial = terminal
    
    


print(wer_classwise)
print(acc_classwise)
print(bleu_classwise)


 accuracy_printerXY(X_val_c,y_val,model)